# Generated by Django 5.1.4 on 2025-01-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hubspot_contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="website",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="zip",
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
