# Generated by Django 5.1.4 on 2025-01-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "hubspot_contacts",
            "0002_contact_address_contact_phone_contact_state_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="phone",
        ),
        migrations.AlterField(
            model_name="contact",
            name="zip",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
