# Generated by Django 5.1.4 on 2025-01-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hubspot_contacts", "0003_remove_contact_phone_alter_contact_zip"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
