# Generated by Django 5.1.4 on 2025-01-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hubspot_contacts", "0004_contact_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
