# Generated by Django 5.1.4 on 2025-01-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hubspot_contacts", "0005_contact_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="email",
        ),
        migrations.AddField(
            model_name="contact",
            name="lastmodifieddate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
