# Generated by Django 5.1.4 on 2025-01-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hubspot_contacts", "0006_remove_contact_email_contact_lastmodifieddate"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="added_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
