# Generated by Django 5.1.4 on 2025-01-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hubspot_contacts", "0007_contact_added_at_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="lastmodifieddate",
            field=models.DateField(auto_now=True),
        ),
    ]
