# Generated by Django 5.1.4 on 2025-01-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hubspot_contacts", "0009_alter_contact_lastmodifieddate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="added_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
